{% set version = "1.13" %}

package:
  name: pypandoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pypandoc/pypandoc-{{ version }}.tar.gz
  sha256: 31652073c7960c2b03570bd1e94f602ca9bc3e70099df5ead4cea98ff5151c1e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.7
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NicklasTegner/pypandoc
  license: MIT
  license_file: LICENSE
  summary: Thin wrapper for pandoc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
