{% set version = "1.7.1" %}

package:
  name: pypandoc
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pypandoc/pypandoc-{{ version }}.tar.gz
  sha256: cc1e1951ab39a8e37a43c820d048aaa2d3fb8ded50fb28b4381b1ddd3ea524d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6,<4.0
    - pip
    - poetry-core >=1.0.0
  run:
    - python >=3.6,<4.0
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"
    - pip check
  requires:
    - pip

about:
  home: https://github.com/NicklasTegner/pypandoc
  license: MIT
  license_file: LICENSE
  summary: Thin wrapper for pandoc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
