{% set version = "1.16.2" %}

package:
  name: pypandoc
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pypandoc/pypandoc-{{ version }}.tar.gz
  sha256: 7a72a9fbf4a5dc700465e384c3bb333d22220efc4e972cb98cf6fc723cdca86b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
  run:
    - python >={{ python_min }}
    - pandoc

test:
  imports:
    - pypandoc
  commands:
    - python -c "import pypandoc; print(pypandoc.get_pandoc_version())"
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NicklasTegner/pypandoc
  license: MIT
  license_file: LICENSE
  summary: Thin wrapper for pandoc

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
